pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=continuous-integration/appveyor/pr
      - status-success=WIP
      - base=master
    actions:
      merge:
        strict: smart
        method: merge
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
