pull_request_rules:
  - name: automatic merge when CI passes and 1 review and not assigned
    conditions:
      - "-author~=dependabot.*"
      - "#approved-reviews-by>=1"
      - "#assignee=0"
      - status-success=continuous-integration/appveyor/pr
      - status-success=WIP
      - base=develop
    actions:
      merge:
        strict: smart
        method: squash
  - name: automatic merge when CI passes and user is AdmiringWorm and not assigned
    conditions:
      - "author=AdmiringWorm"
      - "#assignee=0"
      - status-success=continuous-integration/appveyor/pr
      - status-success=WIP
      - base=develop
    actions:
      merge:
        strict: smart
        method: merge
