@{
  ExcludeRules=@(
    'PSAvoidUsingCmdletAliases',
    'PSAvoidUsingWriteHost',
    'PSUseApprovedVerbs',
    'PSUseShouldProcessForStateChangingFunctions',
    'PSAvoidGlobalVars',
    'PSUseSingularNouns',
    'PSAvoidTrailingWhitespace'
    'PSUseDeclaredVarsMoreThanAssignments'
  )
}
